vim.opt.swapfile = false
vim.opt.backup = false
vim.opt.number = true
vim.opt.cursorline = true
vim.opt.signcolumn = "yes"
vim.opt.laststatus = 3
vim.opt.showmode = false
vim.opt.tabstop = 4
vim.opt.shiftwidth = 4
vim.opt.softtabstop = 4
vim.opt.expandtab = true
vim.opt.autoindent = true
vim.opt.breakindent = true
vim.opt.wrap = false
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.cmd [[ set fillchars+=vert:\  ]]
vim.cmd [[ set fillchars+=vertleft:\  ]]
vim.cmd [[ set fillchars+=vertright:\  ]]
vim.cmd [[ set fillchars+=verthoriz:\  ]]
vim.cmd [[ set fillchars+=horiz:\  ]]
vim.cmd [[ set fillchars+=horizup:\  ]]
vim.cmd [[ set fillchars+=horizdown:\  ]]
