local options = {
  opt = {
    swapfile = false,
    backup = false,
    clipboard = "unnamedplus",
    number = true,
    signcolumn = "yes",
    cursorline = true,
    laststatus = 3,
    showmode = false,
    tabstop = 2,
    shiftwidth = 2,
    autoindent = true,
    breakindent = true,
    expandtab = true,
    wrap = false,
    ignorecase = true,
    smartcase = true,
    timeout = true,
    timeoutlen = 300,
  },
  g = {
    mapleader = " ",
    maplocalleader = ",",
    loaded_2html_plugin = 1,
    loaded_getscript = 1,
    loaded_getscriptPlugin = 1,
    loaded_gzip = 1,
    loaded_logiPat = 1,
    loaded_man = 1,
    loaded_matchit = 1,
    loaded_matchparen = 1,
    loaded_netrwFileHandlers = 1,
    loaded_netrwPlugin = 1,
    loaded_netrwSettings = 1,
    loaded_remote_plugins = 1,
    loaded_rplugin = 1,
    loaded_rrhelper = 1,
    loaded_shada_plugin = 1,
    loaded_shada_plugin = 1,
    loaded_spec = 1,
    loaded_spellfile_plugin = 1,
    loaded_spellfile_plugin = 1,
    loaded_tar = 1,
    loaded_tarPlugin = 1,
    loaded_tutor_mode_plugin = 1,
    loaded_vimball = 1,
    loaded_vimballPlugin = 1,
    loaded_zip = 1,
    loaded_zipPlugin = 1,
    load_black = 1,
    loaded_fzf = 1,
    loaded_gtags = 1,
    loaded_gtags_cscope = 1,
    loaded_node_provider = 0,
    loaded_perl_provider = 0,
    loaded_python3_provider = 0,
    loaded_python_provider = 0,
    loaded_pythonx_provider = 0,
    loaded_ruby_provider = 0,
  },
}

for scope, table in pairs(options) do
  for setting, value in pairs(table) do
    vim[scope][setting] = value
  end
end
